### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by sathibabu-emandi-tm** [codota/tabnine-vscode#410] opened 2021-03-18 05:14 UTC
OS: win32 - x64
 Error: Error
Message: end of central directory record signature not found
Stack: Error: end of central directory record signature not found
    at c:\Users\m1062801\.vscode\extensions\tabnine.tabnine-vscode-3.2.10\node_modules\yauzl\index.js:187:14
    at c:\Users\m1062801\.vscode\extensions\tabnine.tabnine-vscode-3.2.10\node_modules\yauzl\index.js:631:5
    at c:\Users\m1062801\.vscode\extensions\tabnine.tabnine-vscode-3.2.10\node_modules\fd-slicer\index.js:32:7
    at FSReqCallback.wrapper [as oncomplete] (fs.js:524:5)

**Comment by boaz-codota** [comment] 2021-03-29 13:09
We've released a fix.

Duplicate of #383

**Closed by boaz-codota** 2021-03-29 13:09 UTC
