### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by dezfuture** [codota/tabnine-vscode#388] opened 2021-03-17 13:43 UTC
Error: EBUSY: resource busy or locked, open 'C:\Users\Agrim Srivaastava\.vscode\extensions\tabnine.tabnine-vscode-3.2.9\binaries\3.3.96\x86_64-pc-windows-gnu\TabNine-deep-local.exe'

**Comment by dimacodota** [comment] 2021-03-17 14:06
Duplicate of #383

**Closed by dimacodota** 2021-03-17 14:06 UTC
