### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by tirlochanarora16** [codota/tabnine-vscode#385] opened 2021-03-17 11:12 UTC
Error: EBUSY: resource busy or locked, open 'C:\Users\tirlo\.vscode\extensions\tabnine.tabnine-vscode-3.2.9\binaries\3.3.96\x86_64-pc-windows-gnu\WD-TabNine.exe'

**Comment by dimacodota** [comment] 2021-03-17 11:26
Duplicate of #383

**Closed by dimacodota** 2021-03-17 11:26 UTC

**Comment by dimacodota** [comment] 2021-03-17 11:46
@tirlochanarora16 - can you try to restart vscode? does it reproduced?
