### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by sorinstanila** [codota/tabnine-vscode#428] opened 2021-03-18 21:44 UTC
OS: darwin - x64
 Error: Error
Message: ENOENT: no such file or directory, open '/Users/sorinvstanila/.vscode-insiders/extensions/tabnine.tabnine-vscode-3.2.10/binaries/3.3.96/x86_64-apple-darwin/TabNine.zip'
Stack: Error: ENOENT: no such file or directory, open '/Users/sorinvstanila/.vscode-insiders/extensions/tabnine.tabnine-vscode-3.2.10/binaries/3.3.96/x86_64-apple-darwin/TabNine.zip'

**Comment by boaz-codota** [comment] 2021-03-29 13:09
We've released a fix.

Duplicate of #383

**Closed by boaz-codota** 2021-03-29 13:09 UTC
