### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by urmil89** [codota/tabnine-vscode#405] opened 2021-03-18 01:59 UTC
OS: win32 - x64
 Error: Error
Message: getaddrinfo ENOTFOUND update.tabnine.com
Stack: Error: getaddrinfo ENOTFOUND update.tabnine.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)

**Comment by boaz-codota** [comment] 2021-03-29 13:11
We've released a fix.

Duplicate of #383

**Closed by boaz-codota** 2021-03-29 13:11 UTC
