### ISSUE TITLE
why tabnine is taking too much loading time?

### ISSUE THREAD

**Issue by swapnilwagh2204** [codota/tabnine-vscode#472] opened 2021-04-09 04:29 UTC
- Issue Type: `Bug`
- Extension Name: `tabnine-vscode`
- Extension Version: `3.2.17`
- OS Version: `Linux x64 5.4.0-42-generic`
- VSCode version: `1.53.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 8339,
		"activateCallTime": 4,
		"activateResolvedTime": 0,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "TabNine.tabnine-vscode",
				"_lower": "tabnine.tabnine-vscode"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

**Comment by dimacodota** [comment] 2021-04-12 07:36
Duplicate of #458

**Closed by dimacodota** 2021-04-12 07:36 UTC
