### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by roselaguana** [codota/tabnine-vscode#476] opened 2021-04-12 01:16 UTC
- Issue Type: `Bug`
- Extension Name: `tabnine-vscode`
- Extension Version: `3.2.17`
- OS Version: `Darwin x64 20.3.0`
- VS Code version: `1.55.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by dimacodota** [comment] 2021-04-12 07:34
Duplicate of #458

**Closed by dimacodota** 2021-04-12 07:34 UTC
