### ISSUE TITLE
'TabNine.statusBar' not found

### ISSUE THREAD

**Issue by lupin4** [codota/tabnine-vscode#433] opened 2021-03-20 14:57 UTC
**Please complete the following information:**

- OS version: [e.g. Win 10, Mac Catalina]
- Windows 10 Pro
- Editor version [e.g. 1.45.0-insider]:
- VSCode 1.54.3
- Programming language: [e.g. js, ts, c++]
- Python
- TabNine extension version:
- 3.2.13

**If the issue is related to TabNine failure, please provide log files:**

Type `TabNine::config` in your editor, the logs are located at the bottom of the page

**Editor console logs:**

Help -> Toggle Developer Tools

**Issue Details:**

command 'TabNine.statusBar' not found

Tabnine suddenly stopped running, I get the above error if I click on the Tabnine button. Have tried reinstalling and disabling it.

**Comment by shaiahr** [comment] 2021-03-21 05:06
looks like a duplicate of #426

**Closed** 2021-03-29 13:33 UTC
Labels: Status: duplicate
