### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by hind27** [codota/tabnine-vscode#427] opened 2021-03-18 20:57 UTC
OS: win32 - x64
 Error: Error
Message: EBUSY: resource busy or locked, open 'C:\Users\omar\.vscode\extensions\tabnine.tabnine-vscode-3.2.10\binaries\3.3.96\x86_64-pc-windows-gnu\TabNine.exe'
Stack: Error: EBUSY: resource busy or locked, open 'C:\Users\omar\.vscode\extensions\tabnine.tabnine-vscode-3.2.10\binaries\3.3.96\x86_64-pc-windows-gnu\TabNine.exe'

**Comment by boaz-codota** [comment] 2021-03-29 13:09
We've released a fix.

Duplicate of #383

**Closed by boaz-codota** 2021-03-29 13:09 UTC
