### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by xchengL** [codota/tabnine-vscode#407] opened 2021-03-18 02:53 UTC
OS: win32 - x64
 Error: Error
Message: ENOENT: no such file or directory, open 'c:\Users\xcheng\.vscode\extensions\tabnine.tabnine-vscode-3.2.10\binaries\3.3.96\x86_64-pc-windows-gnu\TabNine.zip'
Stack: Error: ENOENT: no such file or directory, open 'c:\Users\xcheng\.vscode\extensions\tabnine.tabnine-vscode-3.2.10\binaries\3.3.96\x86_64-pc-windows-gnu\TabNine.zip'

**Comment by dimacodota** [comment] 2021-03-18 09:43
Duplicate of #402

**Closed by dimacodota** 2021-03-18 09:43 UTC
