### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by VitorHugoPereiraa** [codota/tabnine-vscode#392] opened 2021-03-17 16:31 UTC
OS: win32 - x64
 Error: Error
Message: 262599432:error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT:../../third_party/boringssl/src/crypto/fipsmodule/cipher/e_aes.c:1040:
262599432:error:1000008b:SSL routines:OPENSSL_internal:DECRYPTION_FAILED_OR_BAD_RECORD_MAC:../../third_party/boringssl/src/ssl/tls_record.cc:298:

Stack: Error: 262599432:error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT:../../third_party/boringssl/src/crypto/fipsmodule/cipher/e_aes.c:1040:
262599432:error:1000008b:SSL routines:OPENSSL_internal:DECRYPTION_FAILED_OR_BAD_RECORD_MAC:../../third_party/boringssl/src/ssl/tls_record.cc:298:

**Comment by dimacodota** [comment] 2021-03-18 09:34
Duplicate of #381

**Closed by dimacodota** 2021-03-18 09:34 UTC
