### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by pedrohenriquebr** [codota/tabnine-vscode#180] opened 2020-10-30 17:06 UTC
- Issue Type: `Performance`
- Extension Name: `tabnine-vscode`
- Extension Version: `3.1.5`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.50.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\PEDROH~1\AppData\Local\Temp\TabNine.tabnine-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by boaz-codota** [comment] 2020-11-03 08:51
Hey @pedrohenriquebr thanks for reaching out!

You have not attached the cpuprofile file, only the path to it.

But I suspect that you are talking about TabNine's binary process that is indeed resource consuming due to the fact that it runs a local deep learning model on your computer. If that is the case, the only solution is to use TabNine Professional which runs a bigger model on our GPU servers.

**Comment by dimacodota** [comment] 2021-04-13 18:42
Duplicate of #458

**Closed by dimacodota** 2021-04-13 18:42 UTC
