### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by khalidhardiansyah** [codota/tabnine-vscode#390] opened 2021-03-17 15:54 UTC
OS: win32 - x64
 Error: Error
Message: EBUSY: resource busy or locked, open 'C:\Users\user only\.vscode\extensions\tabnine.tabnine-vscode-3.2.10\binaries\3.3.96\x86_64-pc-windows-gnu\WD-TabNine.exe'
Stack: Error: EBUSY: resource busy or locked, open 'C:\Users\user only\.vscode\extensions\tabnine.tabnine-vscode-3.2.10\binaries\3.3.96\x86_64-pc-windows-gnu\WD-TabNine.exe'

**Comment by dimacodota** [comment] 2021-03-18 09:33
Duplicate of #383

**Closed by dimacodota** 2021-03-18 09:33 UTC
