### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by ProtocolLive** [codota/tabnine-vscode#387] opened 2021-03-17 13:35 UTC
Error: EBUSY: resource busy or locked, open 'C:\Users\fabio\.vscode-insiders\extensions\tabnine.tabnine-vscode-3.2.9\binaries\3.3.96\x86_64-pc-windows-gnu\WD-TabNine.exe'

**Comment by dimacodota** [comment] 2021-03-17 14:06
Duplicate of #383

**Closed** 2021-03-17 14:06 UTC
