### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by helloLari** [codota/tabnine-vscode#456] opened 2021-04-06 19:20 UTC
- Issue Type: `Bug`
- Extension Name: `tabnine-vscode`
- Extension Version: `3.2.16`
- OS Version: `Darwin x64 16.7.0`
- VS Code version: `1.55.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by avnerbarr** [comment] 2021-04-07 08:46
what is the issue?

**Comment by helloLari** [comment] 2021-04-07 11:47
It was appearing incompatible

**Comment by dimacodota** [comment] 2021-04-12 07:35
Duplicate of #458

**Closed by dimacodota** 2021-04-12 07:35 UTC
