### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by Natanlimap** [codota/tabnine-vscode#421] opened 2021-03-18 11:01 UTC
OS: linux - x64
 Error: Error
Message: ETXTBSY: text file is busy, open '/home/natan/.vscode/extensions/tabnine.tabnine-vscode-3.2.10/binaries/3.3.96/x86_64-unknown-linux-musl/TabNine'
Stack: Error: ETXTBSY: text file is busy, open '/home/natan/.vscode/extensions/tabnine.tabnine-vscode-3.2.10/binaries/3.3.96/x86_64-unknown-linux-musl/TabNine'

**Comment by boaz-codota** [comment] 2021-03-29 13:09
We've released a fix.

Duplicate of #383

**Closed by boaz-codota** 2021-03-29 13:09 UTC
