### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by kuduk** [codota/tabnine-vscode#397] opened 2021-03-17 19:01 UTC
OS: win32 - x64
 Error: Error
Message: EPERM: operation not permitted, chmod 'c:\Users\francesco\.vscode\extensions\tabnine.tabnine-vscode-3.2.10\binaries\3.3.96\x86_64-pc-windows-gnu\TabNine.zip'
Stack: Error: EPERM: operation not permitted, chmod 'c:\Users\francesco\.vscode\extensions\tabnine.tabnine-vscode-3.2.10\binaries\3.3.96\x86_64-pc-windows-gnu\TabNine.zip'

**Comment by dimacodota** [comment] 2021-03-18 09:35
Duplicate of #383

**Closed by dimacodota** 2021-03-18 09:35 UTC
