### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by jaggi510** [codota/tabnine-vscode#393] opened 2021-03-17 16:32 UTC
OS: win32 - x64
 Error: Error
Message: read ECONNRESET
Stack: Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)

**Comment by boaz-codota** [comment] 2021-03-29 13:09
We've released a fix.

Duplicate of #383

**Closed by boaz-codota** 2021-03-29 13:09 UTC
