### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by kimseonggon** [codota/tabnine-vscode#404] opened 2021-03-18 01:25 UTC
Error: ENOENT: no such file or directory, unlink '/Users/dohands/.vscode/extensions/tabnine.tabnine-vscode-3.2.9/binaries/3.3.96/x86_64-apple-darwin/TabNine.zip'

**Comment by dimacodota** [comment] 2021-03-18 09:42
Duplicate of #402

**Closed by dimacodota** 2021-03-18 09:42 UTC
