### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by TSMandjon** [codota/tabnine-vscode#394] opened 2021-03-17 17:28 UTC
OS: win32 - x64
 Error: Error
Message: socket hang up
Stack: Error: socket hang up
    at connResetException (internal/errors.js:610:14)
    at TLSSocket.socketOnEnd (_http_client.js:453:23)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by dimacodota** [comment] 2021-03-18 09:44
Duplicate of #386

**Closed by dimacodota** 2021-03-18 09:44 UTC
