### ISSUE TITLE
command 'TabNine.statusBar' not found

### ISSUE THREAD

**Issue by Ogjerry** [codota/tabnine-vscode#386] opened 2021-03-17 12:01 UTC
Error: socket hang up

**Comment by dimacodota** [comment] 2021-03-17 13:32
@Ogjerry - what OS are you using?  are you behind a proxy?

**Comment by Ogjerry** [comment] 2021-03-18 01:36
Hello
I am using windows 10 64 Bit
Yes, I am behind a proxy

Sent from Mail for Windows 10

**Comment by boaz-codota** [comment] 2021-03-29 13:36
Tabnine requires an internet connection to download its engine and models. Please enable such connections for the plugin to work as expected.

Duplicate of #426

**Closed by boaz-codota** 2021-03-29 13:36 UTC
