### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by munnahosssain** [codota/tabnine-vscode#381] opened 2021-03-17 10:12 UTC
Error: 2899286408:error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT:../../third_party/boringssl/src/crypto/fipsmodule/cipher/e_aes.c:1040:
2899286408:error:1000008b:SSL routines:OPENSSL_internal:DECRYPTION_FAILED_OR_BAD_RECORD_MAC:../../third_party/boringssl/src/ssl/tls_record.cc:298:

**Comment by dimacodota** [comment] 2021-03-17 10:38
@munnahosssain  - can you please share your vscode about info?

**Comment by boaz-codota** [comment] 2021-03-29 13:10
We've released a fix.

Duplicate of #383

**Closed by boaz-codota** 2021-03-29 13:10 UTC
