### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by 20enzo** [codota/tabnine-vscode#473] opened 2021-04-09 19:35 UTC
- Issue Type: `Bug`
- Extension Name: `tabnine-vscode`
- Extension Version: `3.2.17`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.55.0`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 17298,
		"activateCallTime": 28,
		"activateResolvedTime": 28,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "TabNine.tabnine-vscode",
				"_lower": "tabnine.tabnine-vscode"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

**Comment by dimacodota** [comment] 2021-04-12 07:35
Duplicate of #458

**Closed by dimacodota** 2021-04-12 07:35 UTC
