### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by thuanan0105** [codota/tabnine-vscode#435] opened 2021-03-21 06:15 UTC
OS: linux - x64
 Error: Error
Message: getaddrinfo EAI_AGAIN update.tabnine.com
Stack: Error: getaddrinfo EAI_AGAIN update.tabnine.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)

**Comment by boaz-codota** [comment] 2021-03-29 13:08
We've released a fix.

Duplicate of #383

**Closed by boaz-codota** 2021-03-29 13:08 UTC
