### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by leo-p-labs** [codota/tabnine-vscode#424] opened 2021-03-18 13:26 UTC
Error: ETXTBSY: text file is busy, open '/home/leo/.vscode/extensions/tabnine.tabnine-vscode-3.2.9/binaries/3.3.96/x86_64-unknown-linux-musl/TabNine'

**Comment by boaz-codota** [comment] 2021-03-29 13:09
We've released a fix.

Duplicate of #383

**Closed by boaz-codota** 2021-03-29 13:09 UTC
