### ISSUE TITLE
Other extensions are not showing up

### ISSUE THREAD

**Issue by are** [codota/tabnine-vscode#6] opened 2018-11-07 12:06 UTC
After installing TabNine, all other autocomplete extensions stopped showing up. Is this intended?

**Comment by jackfranklin** [comment] 2018-11-08 15:14
👍 to this - love this extension but this would be great to be able to configure.

E.g. when I'm working on Elm files I'd love the vscode-elm plugin suggestions (it can intelligently suggest things based on Elm's type system, etc) alongside TabNine's. Right now TabNine seems to take over.

I could disable TabNine for .elm files but then I don't get some of the really useful suggestions.

If it could do both (I'm not sure how VSCode decides which auto complete to use) that would be amazing!

**Comment by jackfranklin** [comment] 2018-11-08 15:35
I think this might be due to the way VSCode scores completion items: https://code.visualstudio.com/docs/extensionAPI/vscode-api#languages.match

**Comment by sergei-dyshel** [comment] 2018-11-11 17:07
@jackfranklin
Unlikely, since TabNine registers completions provider with generic pattern '**' which will give it lower score than any language-specific provider.

**Comment by sergei-dyshel** [comment] 2018-11-11 22:41
Found the root cause, though can not explain it: TabNine registers itself with trigger characters being entire alphabet. When I removed this, other extensions' completions show up in list. I've made a fork which incorporates this fix: https://github.com/sergei-dyshel/tabnine-vscode

**Comment by orzFly** [comment] 2018-11-13 08:47
@sergei-dyshel I installed your fork but TabNine stopped suggesting complex results other than words. This renders TabNine useless in many scenarios.

**Comment by orzFly** [comment] 2018-11-13 08:53
@sergei-dyshel For example, when closing the quotes after `Apple`, the official extension gives this suggestion:

![image](https://user-images.githubusercontent.com/158528/48401547-66aa9000-e764-11e8-88f0-62440c968240.png)

However, it's unavailable in your fork.

**Comment by sergei-dyshel** [comment] 2018-11-13 15:19
@orzFly
Since I removed trigger at every possible character I think now completion would be triggered only if you start typing letters. So, in your example, if it was `func(() => Apple)` instead of `() => Apple`, then you may get completion when typing `hashidType("Apple", f`.

**Comment by sergei-dyshel** [comment] 2018-11-13 15:31
@orzFly 	
![image](https://user-images.githubusercontent.com/6907277/48423767-ed15a080-e769-11e8-8458-3c60481bf1fa.png)

**Comment by jackfranklin** [comment] 2018-11-17 23:04
@sergei-dyshel your fork works really well, thank you! I hope @zxqfl is able to accept a PR :)

**Comment by c-bandy** [comment] 2018-12-14 08:03
It would be great to have this officially incorporated. Thanks for the great PR!

**Comment by sergei-dyshel** [comment] 2018-12-14 08:41
For all interested, I've rebased my fork (https://github.com/sergei-dyshel/tabnine-vscode) on latest master. Currently it's under `master-next` branch but I'll make it `master`. I'll also open PR to the author.

**Comment by jackfranklin** [comment] 2018-12-18 21:52
@zxqfl would you consider a PR to merge some of these changes in? :)

**Comment by neculaesei** [comment] 2019-04-04 08:33
Is this project dead? It starts to feel like this is an unmaintained project, except it's not open-source and we paid for it.

**Comment by zxqfl** [comment] 2019-04-04 13:54
I'm reluctant to make this change because of the issue @orzFly mentioned. I think that in many circumstances, TabNine can offer useful completions when the user has not just typed alphanumeric characters.

@neculaesei, I would be extremely happy to offer you a refund if you wish.

**Comment by DerJacques** [comment] 2019-04-04 14:30
@zxqfl I believe the issue @orzFly mentions has been resolved by the updates @sergei-dyshel has made.

Unfortunately, I feel the benefits Tabnine provides do not outweigh the missing native recommendations. So to me, merging the fork/PR would be really great!

**Comment by sergei-dyshel** [comment] 2019-04-04 15:25
@DerJacques 
There were no updates that fix this issue. Generally I think it can't be fixed due to how autocompletion in vscode works. So right now you have to choose either option:
- Instant autocomplete at any point using full power of TabNine ML but loose many completions provided by other completer.
- Autocomplete identifiers only (or patterns starting with identifies) but use suggestions from other engines.

I agree with @zxqfl that removing completion trigger on all characters also removes many completion opportunities. I think most users will be happy when they're able to configure this option per language.
```json
{
  "tabnine.noAutoTrigger: [
    # list of languages
  ]
}
```

@zxqfl, are you interesed in this kind of patch?

**Comment by JounQin** [comment] 2019-07-17 04:09
Any update? @zxqfl 
This serious problem may prevent a lot of users for this plugin.

**Comment by ctf0** [comment] 2019-07-26 23:47
have the same issue, is it possible for the extension to append to the suggestion list instead of replacing it ?

the only solution is to cancel the list then re-init it again with `ctrl+space` :cry:

**Comment by MattixNow** [comment] 2019-08-22 11:00
Any update it is very frustrating

**Comment by MattixNow** [comment] 2019-08-22 11:01
Any update it is very frustrating

**Comment by sergei-dyshel** [comment] 2019-09-19 00:37
For all interested parties, I've rebased my fork on the last version. Now `tabnine.trigger` controls triggering Tabnine on all characters (utilizing full Tabnine potential but breaking other completion engines) and can be of:
- `on`: enable "all-trigger" in every language
- `off`: disable "all-trigger" for all languages.
- comma-separated list of language IDs to enable "all-trigger" in (and disable in all others).
Enjoy!

**Comment by JounQin** [comment] 2019-09-19 01:07
@sergei-dyshel Better to mention install your fork via https://github.com/sergei-dyshel/tabnine-vscode/blob/master/tabnine-vscode-99.1.10.vsix .

**Comment by zxqfl** [comment] 2019-11-07 09:07
https://github.com/zxqfl/tabnine-vscode/commit/03d2f57c558d441bbac5b635ad97699be9efb2ea tries to fix this issue, please update to tabnine-vscode version 2.1.16 and reply to let me know whether it worked. 

It tries to get the best of both worlds by avoiding suppression while still triggering TabNine on space — if it doesn't work I'll adopt @sergei-dyshel's solution.

**Comment by HenryTSZ** [comment] 2019-11-08 07:29
@zxqfl  Great, perfect solution

**Closed** 2020-12-08 14:52 UTC
