### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Youssefneili** [codota/tabnine-vscode#471] opened 2021-04-08 22:03 UTC
- Issue Type: `Bug`
- Extension Name: `tabnine-vscode`
- Extension Version: `3.2.16`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.55.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by dimacodota** [comment] 2021-04-12 07:35
Duplicate of #458

**Closed by dimacodota** 2021-04-12 07:35 UTC
