### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by sirarthur211** [codota/tabnine-vscode#422] opened 2021-03-18 12:42 UTC
Error: EBUSY: resource busy or locked, open 'C:\Users\kikis\.vscode\extensions\tabnine.tabnine-vscode-3.2.9\binaries\3.3.96\x86_64-pc-windows-gnu\WD-TabNine.exe'

**Comment by boaz-codota** [comment] 2021-03-29 13:09
We've released a fix.

Duplicate of #383

**Closed by boaz-codota** 2021-03-29 13:09 UTC
