### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by abhishekastoorkar** [codota/tabnine-vscode#417] opened 2021-03-18 08:08 UTC
OS: win32 - x64
 Error: Error
Message: end of central directory record signature not found
Stack: Error: end of central directory record signature not found
	at c:\Users\Abhishek.astoorkar\.vscode\extensions\tabnine.tabnine-vscode-3.2.10\node_modules\yauzl\index.js:187:14
	at c:\Users\Abhishek.astoorkar\.vscode\extensions\tabnine.tabnine-vscode-3.2.10\node_modules\yauzl\index.js:631:5
	at c:\Users\Abhishek.astoorkar\.vscode\extensions\tabnine.tabnine-vscode-3.2.10\node_modules\fd-slicer\index.js:32:7
	at FSReqCallback.wrapper [as oncomplete] (fs.js:524:5)

**Comment by dimacodota** [comment] 2021-03-18 09:47
Duplicate of #410

**Closed by dimacodota** 2021-03-18 09:47 UTC
