### ISSUE TITLE
[Download Bundle Error]

### ISSUE THREAD

**Issue by koitoror** [codota/tabnine-vscode#395] opened 2021-03-17 17:54 UTC
OS: win32 - x64
 Error: Error
Message: EBUSY: resource busy or locked, open 'C:\Users\Adm\.vscode\extensions\tabnine.tabnine-vscode-3.2.10\binaries\3.3.96\x86_64-pc-windows-gnu\TabNine-deep-local.exe'
Stack: Error: EBUSY: resource busy or locked, open 'C:\Users\Adm\.vscode\extensions\tabnine.tabnine-vscode-3.2.10\binaries\3.3.96\x86_64-pc-windows-gnu\TabNine-deep-local.exe'

**Comment by dimacodota** [comment] 2021-03-17 18:59
Duplicate of #383

**Closed by dimacodota** 2021-03-17 18:59 UTC
